version: "3"
services:
  db:
    image:  postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"